[tool.poetry]
name = "tankarta-prices"
version = "0.1.0"
description = ""
authors = ["Michal Stanek"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
selenium = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"